# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.twig.cupon_extension:
        class: AppBundle\Twig\Extension\CuponExtension
        tags:
            - { name: twig.extension }
    app.login_listener:
        class: AppBundle\Listener\LoginListener
        arguments: ['@security.authorization_checker', '@router']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.response }
    intl.twig.extension:
        class: Twig_Extensions_Extension_Intl
        tags: [{ name: 'twig.extension' }]
    app.security.oferta_voter:
        class: AppBundle\Security\CreadorOfertaVoter
        arguments: ['@doctrine.orm.entity_manager', '@service_container']
        tags:
            - { name: security.voter }

